# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af9c2cde77474af9baabcb3fdc3acc8a14ddf468e84fc99656bffdb4c3ca6267691ab7748242ec600989e5a9f4a721d7ba85f6ca3aa54acde3b007c69b548ad7
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>

test:
  secret_key_base: d179587d7fed4ca84ba6827b8f4159780a10ce43fe23ce97341864ab44c83662e34bffd59f114703556417711c607646dcf9984bd801a7bf56b794c67a179167

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
